### ISSUE TITLE
composer authentication failed

### ISSUE THREAD

**Issue by NickvdMeij** [mageinferno/magento2-docker-compose#31] opened 2016-10-22 10:29 UTC
When deploying the docker-compose on my digital ocean server (make with the docker-machine create command) I get this composer error. 

`
[Composer\Downloader\TransportException]
`
`
The 'https://repo.magento.com/packages.json' URL required authentication.
`
`
You must be using the interactive console to authenticate
`

When i change the volume of app data to ./composer/.compose (and ofcourse create the nessesary auth.json in this folder) it works locally, but not when deploy it on my production server. I google the problem and found that there is also a command that can be used:

`
CMD composer config --global http-basic.repo.magento.com PUBLIC_KEY PRIVATE_KEY
`

to set the correct auth.json. Sadly this didnt do much either. Any idea whats wrong?

**Comment by markoshust** [comment] 2016-11-04 12:58
I'm fixing this right now. This is due to the way composer is being mounted.

**Comment by markoshust** [comment] 2016-11-04 14:16
dupe of https://github.com/mageinferno/docker-magento2-php/issues/18 -- hang tight new build coming which fixes all of this :)

**Closed by markoshust** 2016-11-04 14:16 UTC

**Comment by markoshust** [comment] 2016-11-04 16:56
All built:
https://hub.docker.com/r/mageinferno/magento2-php/builds/
https://hub.docker.com/r/mageinferno/magento2-nginx/builds/

Note that these new dir's depend/mount to `/var/www/html` instead of `/srv/www`. The `www-data` user's home directory was `/var/www`, and the simplest change to get all the composer functionality working correctly was to change to this dir.

I just release 5.0.0 of the docker-compose file to https://github.com/mageinferno/magento2-docker-compose -- mainly a ton of fixes for composer. Automated builds with composer and all other composer functionality should now work with zero errors. This also brings back the ability to mount the composer cache from the host to the container, saving a ton of time with installs.
