### ISSUE TITLE
ValueError: Timeout value connect was timeout

### ISSUE THREAD

**Issue by wickywills** [mageinferno/magento2-docker-compose#69] opened 2017-07-18 08:53 UTC
Receiving the following when trying to run this:

```Traceback (most recent call last):
      File "/home/wickywills/.local/bin/docker-compose", line 11, in <module>
        sys.exit(main())
      File "/home/wickywills/.local/lib/python2.7/site-packages/compose/cli/main.py", line 68, in main
        command()
      File "/home/wickywills/.local/lib/python2.7/site-packages/compose/cli/main.py", line 118, in perform_command
        handler(command, command_options)
      File "/home/wickywills/.local/lib/python2.7/site-packages/compose/cli/main.py", line 750, in run
        run_one_off_container(container_options, self.project, service, options)
      File "/home/wickywills/.local/lib/python2.7/site-packages/compose/cli/main.py", line 1136, in run_one_off_container
        rescale=False
      File "/home/wickywills/.local/lib/python2.7/site-packages/compose/project.py", line 388, in up
        warn_for_swarm_mode(self.client)
      File "/home/wickywills/.local/lib/python2.7/site-packages/compose/project.py", line 614, in warn_for_swarm_mode
        info = client.info()
      File "/home/wickywills/.local/lib/python2.7/site-packages/docker/api/daemon.py", line 90, in info
        return self._result(self._get(self._url("/info")), True)
      File "/home/wickywills/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
        return f(self, *args, **kwargs)
      File "/home/wickywills/.local/lib/python2.7/site-packages/docker/api/client.py", line 189, in _get
        return self.get(url, **self._set_request_timeout(kwargs))
      File "/home/wickywills/.local/lib/python2.7/site-packages/requests/sessions.py", line 515, in get
        return self.request('GET', url, **kwargs)
      File "/home/wickywills/.local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/wickywills/.local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
        r = adapter.send(request, **kwargs)
      File "/home/wickywills/.local/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
        timeout=timeout
      File "/home/wickywills/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 582, in urlopen
        timeout_obj = self._get_timeout(timeout)
      File "/home/wickywills/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 309, in _get_timeout
        return Timeout.from_float(timeout)
      File "/home/wickywills/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
        return Timeout(read=timeout, connect=timeout)
      File "/home/wickywills/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
        self._connect = self._validate_timeout(connect, 'connect')
      File "/home/wickywills/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
        "int or float." % (name, value))
    ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.

Seems like this is a common issue, but no real solution. I am running Ubuntu 16.10, and followed the installation instructions as per the Docker documentation. Can anyone advise?
```

Any ideas?

**Comment by markoshust** [comment] 2017-07-18 13:23
Closing due to lack of detail. Need: exact command being ran, actual output, desired output, steps to reproduce

**Closed by markoshust** 2017-07-18 13:23 UTC
