### ISSUE TITLE
Fatal error: Uncaught ErrorException: session_write_close()

### ISSUE THREAD

**Issue by jagwire16** [mageinferno/magento2-docker-compose#8] opened 2016-01-29 15:52 UTC
It looks like you're making great progress. I tried the install and received the errors below. I'm not sure that it's breaking anything, but it seems like it is worth a look.

```
[Progress: 361 / 362]
Post installation file permissions check...
For security, remove write permissions from these directories: '/src/app/etc'
[Progress: 362 / 362]
[SUCCESS]: Magento installation complete.
[SUCCESS]: Magento Admin URI: /admin_12j6z3

Fatal error: Uncaught ErrorException: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/src/var/session/) in /src/vendor/magento/framework/Session/SessionManager.php:139
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'session_write_c...', '/src/vendor/mag...', 139, Array)
#1 /src/vendor/magento/framework/Session/SessionManager.php(139): session_write_close()
#2 [internal function]: Magento\Framework\Session\SessionManager->writeClose()
#3 {main}
  thrown in /src/vendor/magento/framework/Session/SessionManager.php on line 139
Reindexing all indexes...
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:02
Catalog Rule Product index has been rebuilt successfully in 00:00:01
Catalog Product Rule index has been rebuilt successfully in 00:00:00

Fatal error: Uncaught ErrorException: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/src/var/session/) in /src/vendor/magento/framework/Session/SessionManager.php:139
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'session_write_c...', '/src/vendor/mag...', 139, Array)
#1 /src/vendor/magento/framework/Session/SessionManager.php(139): session_write_close()
#2 [internal function]: Magento\Framework\Session\SessionManager->writeClose()
#3 {main}
  thrown in /src/vendor/magento/framework/Session/SessionManager.php on line 139
Deploying static view files...
Requested languages: en_US
=== frontend -> Magento/blank -> en_US ===
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Successful: 1965 files; errors: 0
---

```

**Comment by markoshust** [comment] 2016-01-29 18:14
Hi @jagwire16, which php image are you using? Note that 'latest' shouldn't be used anymore.

The most recent is mageinferno/php-fpm:7.0.2-fpm-1

Cheers,
Mark

**Comment by jagwire16** [comment] 2016-02-01 14:39
As of this writing, it looks like you're using mageinferno/magento2-php:7.0.2-fpm-0. I updated the version locally to mageinferno/magento2-php:7.0.2-fpm-1 and I'm still getting this error.

**Comment by brideo** [comment] 2016-02-09 10:23
Hi Mark,

I'm getting the same issue, I think the problem may be with file permissions which are not being set properly.

Are you able to replicate this issue or do you need more details?

**Comment by markoshust** [comment] 2016-02-09 21:51
This is most likely related to https://github.com/mageinferno/magento2-docker-compose/issues/5

**Comment by brideo** [comment] 2016-02-09 22:03
Looks that way, thanks. :)

**Comment by markoshust** [comment] 2016-03-15 02:24
I'm closing this as a dupe of https://github.com/mageinferno/magento2-docker-compose/issues/5

**Closed by markoshust** 2016-03-15 02:24 UTC
